### ISSUE TITLE
Misses to say start of text

### ISSUE THREAD

**Issue by nkrth** [nateshmbhat/pyttsx3#181]
Tried running in Python 3.9.1
```
>>> import pyttsx3
>>> engine = pyttsx3.init()
>>> engine.say("1 2 3 4 5 6 7 8 9")
>>> engine.runAndWait()
>>> engine.say("a b c d e f g h i j k l m n o p q r s t u v w x y z")
>>> engine.runAndWait()
```
It starts at 4 5 6 7 8 9
and it starts at e f g ...

Also, I saved this to a file and tried running, it doesn't work. (no traceback or audio)
I'm using Windows 10. Hope this isn't just my issue.

**Comment by jks7592** [comment]
I have the same issue. I'm using a raspberry pi 4 with Raspian OS and python 3.7.3. When I use HDMI as the audio output it starts at letter e, while using headphones in the AV jack it starts at letter a.

**Comment by lcnittl** [comment]
I believe that the problem is that sound is deactivated over HDMI, if not used. Turning it back on takes a bit of time. You have to keep the socket up by running e.g. `play -qn`, essentially playing a null sound in the background which keeps it from going to sleep.

Cf.: https://unix.stackexchange.com/questions/362223/short-audio-playback-is-muted-requires-warming-up-or-secondary-audio-in-backgro

I did this in one of my script with a helper function

```py
import shlex
import subprocess

def keep_sound_alive() -> None:
    cmd = "play -qn"
    subprocess.Popen(  # nosec: B603
        shlex.split(cmd), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )
    sleep(1)
```

that I execute once on startup of the script

```py
keep_sound_alive()
```

Let me know if that fixed your problem.

And if it did, maybe something like this can be added to the `pyttsx3.init()` method of `pyttsx3` - either whenever running on linux (I think this is a problem only there) or with a (`hdmi` ?) parameter.

PS: Sorry for all the (certainly) wrong terminology :grin:

**Comment by TotallyAProgrammer** [comment]
@lcnittl The issue with that code is that it executes a command in a shell that is not guaranteed to exist. This adds a large layer of complexity to the library, not in code complexity itself, but dependency complexity and checking for their existence, etc. This also creates possible security concerns, because (If i remember right) all shell commands executed, are executed with the same privileges as the user running the program.
While I think this is a good idea, and actually a good solution to this recurring problem, it needs some polishing and research. If you can find a way to implement a NULL sound into the program, I'll gladly write the code, and fully implement it into the init

**Comment by lcnittl** [comment]
@TotallyAProgrammer Yes, my way is certainly not the way to go for the library, but was intended for @jks7592. Plus, for the library it must work cross-platform, which my snippet does not.

In the meantime, would you consider adding this info to the docs, so that users can think of their own way of solving this, without being surprised by cut sound? (Or it might be there already, in that case, mea culpa)

This here is not meant for a solution for the library, but maybe for @nkrth:
* For Win10 there is an external tool that claims to solve this problem: https://veg.by/en/projects/soundkeeper/
* For Linux use `play -qn` (no need to run it from within the script, can also be run as service on startup)
* For Mac - sorry, no idea
