### ISSUE TITLE
How to use Use NSSpeechSynthesizer in a Linux or a Docker environment

### ISSUE THREAD

**Issue by rishab-sharma** [nateshmbhat/pyttsx3#185]
I am really new to this domain,

I synthesized two samples of voices, one in Linux and one in Mac

I liked the quality of speech synthesized in Mac as compared to the one in Linux. I used the pyttsx3 module in its default setting in both environments, so I think the main difference behind the quality is the difference in NSSpeechSynthesizer and espeak drivers of Mac and Linux respectively. 

If I am wrong in my above assumption please let me know, else how can I get the Mac Quality of the speech in my Linux based cloud or shall I go for a Mac-based container. 

Can anyone help me with a Dockerfile for the Mac-based container where I can run pyttsx3 with NSSpeechSynthesizer?
Also if we can get NSSpeechSynthesizer in Linux, that will be great too 

Can you help me with this @nateshmbhat @TotallyAProgrammer @hobson

**Comment by TotallyAProgrammer** [comment]
Yes, you are correct in what you are saying. In order to get NSS on linux though you would have to find its source and probably build it from that, as i dont think there are any linux built versions of it (MacOS is BSD based). Im also not sure if a source code version of it even exists. This is something that might take a little bit of research.

**Comment by willwade** [comment]
I’m not saying impossible but it’s not going to be easy this. You’d be far better using nuance paid for voices since most of the apple voices are from nuance vocalizer. But really if you are Linux look at https://github.com/rhasspy/piper
