### ISSUE TITLE
Installation error (PyPI) for 2.80 (Linux and Windows)

### ISSUE THREAD

**Issue by pnhofmann** [nateshmbhat/pyttsx3#82]
Taken from 'pyttsx3-2.80.dist-info/METADATA' of latest .whl package from [mypy](https://pypi.org/project/pyttsx3/):

```
Requires-Dist: pyobjc (>=2.4)
Requires-Dist: pyobjc (>=2.4) ; "darwin" in sys_platform
Requires-Dist: comtypes ; "win32" in sys_platform
```

I don't understand why, but somehow 'pyobjc' is duplicated. Therefore pip wrongly tries to install pyobjc on Linux or Windows platforms - which of course fails since pyobjc is MacOS-only.

**Comment by asottile** [comment]
the fix is to delete the following lines:

https://github.com/nateshmbhat/pyttsx3/blob/7f87def5b5844afd69b7d9dfb2629ae5694308f7/setup.py#L14-L23

https://github.com/nateshmbhat/pyttsx3/blob/7f87def5b5844afd69b7d9dfb2629ae5694308f7/setup.py#L40

(these are unnecessary due to the platform-specific `extras_require`)
